### ISSUE TITLE
Do you think you method could be extended to dense prediction

### ISSUE THREAD

**Issue by gaopeng-eugene** [tkipf/gcn#11]
Here is an concrete example. In image segmentation, we could represent the image by superpixel. Superpixel, by itself, can be seen as a irregular graph which is the exact scene your model designed to solve.

**Comment by tkipf** [comment]
Thanks for your question. Have a look at the Mixture Model CNN paper: https://arxiv.org/abs/1611.08402 - they explored applying such a model under the scenario you described. They found that using a slightly more general propagation function (as compared to the spectrally motivated approach from the GCN paper) works better in this case.
