### ISSUE TITLE
Formatted data for karate example from appendices?

### ISSUE THREAD

**Issue by jbrjake** [tkipf/gcn#12]
Hi, I was wondering if data for the Zachary's Karate Club examples in the appendices to the paper are available? I know the karate dataset itself is widely available, but I'm looking for a version that's already got Planetoid-style formatting applied, so it can be loaded directly into the gcn scripts.

**Comment by tkipf** [comment]
Hi, I'd recommend writing your own parser for this case. I can share the parser that I wrote for https://github.com/tkipf/kegra - for the GCN repository you might need to make some adjustments.

```
def load_karate(path="data/karate-club/"):
    """Load karate club dataset"""
    print('Loading karate club dataset...')

    edges = np.loadtxt("{}edges.txt".format(path), dtype=np.int32) - 1  # 0-based indexing
    features = sp.eye(np.max(edges+1), dtype=np.float32).tocsr()
    idx_labels = np.loadtxt("{}mod-based-clusters.txt".format(path), dtype=np.int32)
    idx_labels = idx_labels[idx_labels[:, 0].argsort()]
    labels = encode_onehot(idx_labels[:, 1])

    adj = sp.coo_matrix((np.ones(edges.shape[0]), (edges[:, 0], edges[:, 1])),
                        shape=(labels.shape[0], labels.shape[0]), dtype=np.float32)

    # build symmetric adjacency matrix
    adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)

    print('Dataset has {} nodes, {} edges, {} features.'.format(adj.shape[0], edges.shape[0], features.shape[1]))
    return features.todense(), adj, labels, edges
```

Data below:

`edges.txt`:

```
1 32
1 22
1 20
1 18
1 14
1 13
1 12
1 11
1 9
1 8
1 7
1 6
1 5
1 4
1 3
1 2
2 31
2 22
2 20
2 18
2 14
2 8
2 4
2 3
3 14
3 9
3 10
3 33
3 29
3 28
3 8
3 4
4 14
4 13
4 8
5 11
5 7
6 17
6 11
6 7
7 17
9 34
9 33
9 33
10 34
14 34
15 34
15 33
16 34
16 33
19 34
19 33
20 34
21 34
21 33
23 34
23 33
24 30
24 34
24 33
24 28
24 26
25 32
25 28
25 26
26 32
27 34
27 30
28 34
29 34
29 32
30 34
30 33
31 34
31 33
32 34
32 33
33 34
```

`mod-based-clusters.txt`:
```
7 0
5 0
11 0
6 0
17 0
12 1
13 1
1 1
18 1
22 1
8 1
4 1
2 1
20 1
14 1
3 2
32 2
10 2
29 2
28 2
26 2
25 2
9 3
31 3
34 3
33 3
21 3
24 3
15 3
16 3
23 3
19 3
30 3
27 3
```

**Comment by jbrjake** [comment]
Thank you, that's very helpful :)

**Comment by mimisen-boop** [comment]
What should be the proper size of `idx_train`, `idx_val`, and `idx_test` in `get_splits()` for karate-club graph dataset? And your parser has 4 return value, the question is how do you use `edges` in your karate-club dataset parser? 
Or can I use it without `edges`,  returning only `features.todense()`, `adj`, and `labels` just like cora dataset?
