### ISSUE TITLE
can't print

### ISSUE THREAD

**Issue by J-cabin** [tkipf/gcn#121]
When I add print("XXX") in any other files except train.py (GCN __init function for example), the contents can't be shown in terminal. Could anybody explain for me?

**Comment by DivyaLekha** [comment]
Could you find why?

**Comment by J-cabin** [comment]
Not yet.

**Comment by winddd** [comment]
The project was installed before you run it. So if you modify it, you need to reinstall.

**Comment by J-cabin** [comment]
Oh, that's it, thank you!
