### ISSUE TITLE
How to format data for util?

### ISSUE THREAD

**Issue by ch3njust1n** [tkipf/gcn#13]
Some general questions:
How do I format my data so that it can be processed by util? Should I store my data in a .txt file? How should that data look like? What are these .allx .ally and .graph files?

**Comment by tkipf** [comment]
Thanks for your question. `.allx`, `.ally` and `.graph` are just pickled numpy files. For new data, you should write your own parser / data loading function along the lines of:

```
def load_data(dataset_str):
    """Load data."""
    names = ['x', 'y', 'tx', 'ty', 'allx', 'ally', 'graph']
    objects = []
    for i in range(len(names)):
        with open("data/ind.{}.{}".format(dataset_str, names[i]), 'rb') as f:
            if sys.version_info > (3, 0):
                objects.append(pkl.load(f, encoding='latin1'))
            else:
                objects.append(pkl.load(f))

    x, y, tx, ty, allx, ally, graph = tuple(objects)
    test_idx_reorder = parse_index_file("data/ind.{}.test.index".format(dataset_str))
    test_idx_range = np.sort(test_idx_reorder)

    if dataset_str == 'citeseer':
        # Fix citeseer dataset (there are some isolated nodes in the graph)
        # Find isolated nodes, add them as zero-vecs into the right position
        test_idx_range_full = range(min(test_idx_reorder), max(test_idx_reorder)+1)
        tx_extended = sp.lil_matrix((len(test_idx_range_full), x.shape[1]))
        tx_extended[test_idx_range-min(test_idx_range), :] = tx
        tx = tx_extended
        ty_extended = np.zeros((len(test_idx_range_full), y.shape[1]))
        ty_extended[test_idx_range-min(test_idx_range), :] = ty
        ty = ty_extended

    features = sp.vstack((allx, tx)).tolil()
    features[test_idx_reorder, :] = features[test_idx_range, :]
    adj = nx.adjacency_matrix(nx.from_dict_of_lists(graph))

    labels = np.vstack((ally, ty))
    labels[test_idx_reorder, :] = labels[test_idx_range, :]

    idx_test = test_idx_range.tolist()
    idx_train = range(len(y))
    idx_val = range(len(y), len(y)+500)

    train_mask = sample_mask(idx_train, labels.shape[0])
    val_mask = sample_mask(idx_val, labels.shape[0])
    test_mask = sample_mask(idx_test, labels.shape[0])

    y_train = np.zeros(labels.shape)
    y_val = np.zeros(labels.shape)
    y_test = np.zeros(labels.shape)
    y_train[train_mask, :] = labels[train_mask, :]
    y_val[val_mask, :] = labels[val_mask, :]
    y_test[test_mask, :] = labels[test_mask, :]

    return adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask
```

**Comment by AldoMarzullo** [comment]
Hi, Thank you for this implementation!

Sorry for the trivial and maybe duplicated question. Could you, please, clarify the meaning of `idx_` and `_mask`. It seems not immediate for me.

**Comment by tkipf** [comment]
Thanks for your question! Both `idx_[train,test,val]` and `[train,test,val]_mask` carry the same information: they indicate the respective nodes that should participate in the loss function (or in the calculation of any other metric, such as accuracy). `idx_[train,test,val]` is an index vector (containing all relevant node indices in arbitrary order) whereas `[train,test,val]_mask` is a binary vector of length `total_num_nodes` indicating the same nodes as `idx_[train,test,val]`. In principle, either one of these will be sufficient, but we pass both of them for convenience.

**Comment by YasmeenaAkhter** [comment]
How can we use .csv file like iris classification/cancer classification in the above-given format?

**Comment by fansariadeh** [comment]
> Thanks for your question. `.allx`, `.ally` and `.graph` are just pickled numpy files. For new data, you should write your own parser / data loading function along the lines of:
> 
> ```
> def load_data(dataset_str):
>     """Load data."""
>     names = ['x', 'y', 'tx', 'ty', 'allx', 'ally', 'graph']
>     objects = []
>     for i in range(len(names)):
>         with open("data/ind.{}.{}".format(dataset_str, names[i]), 'rb') as f:
>             if sys.version_info > (3, 0):
>                 objects.append(pkl.load(f, encoding='latin1'))
>             else:
>                 objects.append(pkl.load(f))
> 
>     x, y, tx, ty, allx, ally, graph = tuple(objects)
>     test_idx_reorder = parse_index_file("data/ind.{}.test.index".format(dataset_str))
>     test_idx_range = np.sort(test_idx_reorder)
> 
>     features = sp.vstack((allx, tx)).tolil()
>     features[test_idx_reorder, :] = features[test_idx_range, :]
>     adj = nx.adjacency_matrix(nx.from_dict_of_lists(graph))
> 
>     labels = np.vstack((ally, ty))
>     labels[test_idx_reorder, :] = labels[test_idx_range, :]
> 
>     idx_test = test_idx_range.tolist()
>     idx_train = range(len(y))
>     idx_val = range(len(y), len(y)+500)
> 
>     train_mask = sample_mask(idx_train, labels.shape[0])
>     val_mask = sample_mask(idx_val, labels.shape[0])
>     test_mask = sample_mask(idx_test, labels.shape[0])
> 
>     y_train = np.zeros(labels.shape)
>     y_val = np.zeros(labels.shape)
>     y_test = np.zeros(labels.shape)
>     y_train[train_mask, :] = labels[train_mask, :]
>     y_val[val_mask, :] = labels[val_mask, :]
>     y_test[test_mask, :] = labels[test_mask, :]
> 
>     return adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask
> ```
> 
> Essentially, you need to provide these variables: `adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask`. `adj` is a sparse NxN matrix (N: number of nodes) and `features` is a sparse NxD matrix (D number of features). Otherwise you just need `idx_train`, `idx_val` and `idx_test` lists (lists of node indices) and a dense NxK (K: number of classes) one-hot label matrix `labels` - if you decide to use the above pre-processing code to get `y_train, y_val, y_test, train_mask, val_mask, test_mask`.

Dear Kipf,
Can you please explain more how to perform " parse_index_file"? 
Many thanks

**Comment by KKaranKK** [comment]
> > Thanks for your question. `.allx`, `.ally` and `.graph` are just pickled numpy files. For new data, you should write your own parser / data loading function along the lines of:
> > ```
> > def load_data(dataset_str):
> >     """Load data."""
> >     names = ['x', 'y', 'tx', 'ty', 'allx', 'ally', 'graph']
> >     objects = []
> >     for i in range(len(names)):
> >         with open("data/ind.{}.{}".format(dataset_str, names[i]), 'rb') as f:
> >             if sys.version_info > (3, 0):
> >                 objects.append(pkl.load(f, encoding='latin1'))
> >             else:
> >                 objects.append(pkl.load(f))
> > 
> >     x, y, tx, ty, allx, ally, graph = tuple(objects)
> >     test_idx_reorder = parse_index_file("data/ind.{}.test.index".format(dataset_str))
> >     test_idx_range = np.sort(test_idx_reorder)
> > 
> >     features = sp.vstack((allx, tx)).tolil()
> >     features[test_idx_reorder, :] = features[test_idx_range, :]
> >     adj = nx.adjacency_matrix(nx.from_dict_of_lists(graph))
> > 
> >     labels = np.vstack((ally, ty))
> >     labels[test_idx_reorder, :] = labels[test_idx_range, :]
> > 
> >     idx_test = test_idx_range.tolist()
> >     idx_train = range(len(y))
> >     idx_val = range(len(y), len(y)+500)
> > 
> >     train_mask = sample_mask(idx_train, labels.shape[0])
> >     val_mask = sample_mask(idx_val, labels.shape[0])
> >     test_mask = sample_mask(idx_test, labels.shape[0])
> > 
> >     y_train = np.zeros(labels.shape)
> >     y_val = np.zeros(labels.shape)
> >     y_test = np.zeros(labels.shape)
> >     y_train[train_mask, :] = labels[train_mask, :]
> >     y_val[val_mask, :] = labels[val_mask, :]
> >     y_test[test_mask, :] = labels[test_mask, :]
> > 
> >     return adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Essentially, you need to provide these variables: `adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask`. `adj` is a sparse NxN matrix (N: number of nodes) and `features` is a sparse NxD matrix (D number of features). Otherwise you just need `idx_train`, `idx_val` and `idx_test` lists (lists of node indices) and a dense NxK (K: number of classes) one-hot label matrix `labels` - if you decide to use the above pre-processing code to get `y_train, y_val, y_test, train_mask, val_mask, test_mask`.
> 
> Dear Kipf,
> Can you please explain more how to perform " parse_index_file"?
> Many thanks

it is simply a function defined in utils.py only
```
def parse_index_file(filename):
    """Parse index file."""
    index = []
    for line in open(filename):
        index.append(int(line.strip()))
    return index
```
