### ISSUE TITLE
About the input data,the N by N adjacency matrix (N is the number of nodes)

### ISSUE THREAD

**Issue by Ningshiqi** [tkipf/gcn#19]
The matrix must be the adjacency which is filled with 0 or 1?
Can it be the weight whthin [0,1]?
For explame,the similarity of nodes.
Thank you for your reply!

**Comment by tkipf** [comment]
It is also possible to provide a weighted graph with any numerical value on the edges! Hope this helps.

**Comment by Ningshiqi** [comment]
Thank you for your fast reply!It helps me a lot!
