### ISSUE TITLE
prediction not fully worked

### ISSUE THREAD

**Issue by sufengniu** [tkipf/gcn#2]
Hello,

it seems that if I extract the prediction output in train.py line 
`outs = sess.run([model.opt_op, model.loss, model.accuracy], feed_dict=feed_dict)`
as
`outs = sess.run([model.opt_op, model.loss, model.accuracy, model.predict], feed_dict=feed_dict)`

the code will failed to extract the prediction results, do you have any idea how to fix it?

Thank you

**Comment by sufengniu** [comment]
My bad, I just found that it should be model.predict() instead of model.predict. however, I found the output of model.predict sizes full data set (including training, testing, validation). should it here to be just training? since the train_mask has been passed into the feed_dict

Thank you

**Comment by tkipf** [comment]
No worries. What you describe is actually the intended behavior of the model. The setting we consider in this implementation is the following: we train on both labeled and unlabeled examples (i.e. semi-supervised learning) and later evaluate the predictions of the trained model on previously unlabeled examples. In this setting, the model always performs a forward pass on the full dataset, the mask only affects which labels are available to the model. All other nodes are treated as unlabeled nodes.

**Comment by sufengniu** [comment]
Thank you, I found it. Just wondering did you ever try the gcn on multi-label graph (blogcatalog)? I tried it, and it seems the performance is very poor. I basically change your softmax_cross_entropy to sigmoid_cross_entropy (and I masked each label). not sure if this is caused by code problem or model.

**Comment by tkipf** [comment]
I have not yet looked at multi-label classification, but it would be interesting to investigate this further.

**Comment by sufengniu** [comment]
Thank you, will close the issue
