### ISSUE TITLE
Something about the adjacency matrix

### ISSUE THREAD

**Issue by l11x0m7** [tkipf/gcn#20]
It seems that the N by N adjacency matrix is required but not used in your code, is it?

**Comment by trdavidson** [comment]
The NxN adjacency matrix is required to create the Laplacian needed for the graph convolution. 

L = I - D^(-0.5)AD^(-0.5), where L is the symmetrically normalized laplacian, D the degree matrix, I the identity and A the adjacency matrix. See https://en.m.wikipedia.org/wiki/Laplacian_matrix, for more details.

**Comment by tkipf** [comment]
> It seems that the N by N adjacency matrix is required

Yes, this is correct.

> but not used in your code

Not quite, the adjacency matrix is fed for the `support` placeholder.

**Comment by shuaishuaij** [comment]
However, why there is no processing of the D matrix in the code? (the degree matrix)
