### ISSUE TITLE
Can your convolution method be applied to an arbitrary graph (irrigular graph) ?

### ISSUE THREAD

**Issue by pinkfloyd06** [tkipf/gcn#23]
Let me first thank you for your work.

l would like to ask you whether your graph convolution method can be applied to an arbitrary graph such as an irregular graph  ( variable number of edges and vertices) ?

Thank you

Thank you

**Comment by tkipf** [comment]
Yes, that is possible and tends to work just fine.

**Comment by pinkfloyd06** [comment]
Thank you
