### ISSUE TITLE
chebyshev polynomial degree is of order 1 or 3 ?

### ISSUE THREAD

**Issue by pinkfloyd06** [tkipf/gcn#25]
Hello,

In the paper it's mentioned that you use first order  chebyshev k=1. However in your implementation : 

https://github.com/tkipf/gcn/blob/master/gcn/train.py#L26

and 
https://github.com/tkipf/gcn/blob/master/gcn/utils.py#L131

it seems that you go up to k=3  and the algorithm needs at list k=2 

Thank you for your clarification

**Comment by tkipf** [comment]
This is a general implementation that supports any order K.
