### ISSUE TITLE
Divide by 0 warning with TensorFlow backend while load AIFB dataset

### ISSUE THREAD

**Issue by TheThirstyCrow** [tkipf/gcn#26]
Hi,

I am trying to emulate the results reported in your papers. I am using this command:-
python train.py -d aifb --bases 0 --hidden 16 --l2norm 0. --testing

When I use the tensorflow backend in Keras I get this warning:
train.py:81: RuntimeWarning: divide by zero encountered in divide
 d_inv = 1. / d
I was wondering if this is a bug? Any pointers would be appreciated.

P.S. - There is no such warning when I use Theano as the backend. 

Thanks.

**Comment by tkipf** [comment]
Hi, thanks for reporting this. I suppose your question is with regards to the following repository: https://github.com/tkipf/relational-gcn

The behavior is intended, as we catch any "inf" values originating from division by zero in the next line. This is quite hacky and there are better ways to do it, but it does the job.
