### ISSUE TITLE
How can we make a multi layer perceptron on graph ?

### ISSUE THREAD

**Issue by pinkfloyd06** [tkipf/gcn#27]
Hello @tkipf ,

Sorry for my stupid question, but l'm wondering if we can apply a multi layer perceptron on graph data ?
with graph convnet we apply convolution in spectral domain using graph laplacian . What could be the equivalent of that for MLP ?

Thank you

**Comment by tkipf** [comment]
You can simply ignore the graph structure and run an MLP on each node separately. That was one of the baselines in our ICLR2017 paper. You could also featuring the adjacency matrix. For node classification, simply treat the adjacency vector of a node as a feature vector. You can do the same with graph-level models where you flatten the whole adjacency matrix and treat it as a feature vector. In practice this works surprisingly well, but is not covariant to permutations and doesn’t generalize when you add or remove nodes. Also adding or removing edges can be problematic.

**Comment by pinkfloyd06** [comment]
Thank you for your answer. 
A nuance on graph classification.

Suppose that we have a sample of 10 example where each example has 20 nodes and each node has 3 values.

`Sample=(10,20,3)`

and  adjacecny matrix of each example will be of dim=(20,20)

`Adjacecny=(10,20,20)`

By flattening you mean : 

for each node we extract its adjacency vector (which is of length 20) and add the 20 values to node features . Hence, we go from :  

`Sample=(10,20,3)`
to `Sample=(10,20,3+20)`

Isn't it ?

**Comment by tkipf** [comment]
By flattening I mean: constructing a M*N dimensional vector from a M by N
matrix.

**Comment by pinkfloyd06** [comment]
Ok.

Always in the context of graph classification  :  

Let's suppose you have N=20 nodes then your adjacency matrix is of dimension=[20,20]

Then you build a N*N feature vector based on adjacency matrix  N*N = 20*20=400 then you feed it to MLP.
So if l understand, your idea is to train the MLP  using adjacency matrix as a feature vector. What about the feature values of each node ? do you ignore them ?

**Comment by tkipf** [comment]
> Then you build a NN feature vector based on adjacency matrix NN = 20*20=400 then you feed it to MLP.
So if l understand, your idea is to train the MLP using adjacency matrix as a feature vector.

Yes, exactly.

> So if l understand, your idea is to train the MLP using adjacency matrix as a feature vector. What about the feature values of each node ? do you ignore them ?

You can concatenate them and append them to the "adjacency feature vector". All in all, this is a very poor modeling choice as it does not respect the permutation covariances/invariances for graphs, but it is still an interesting baseline that can work well in some cases.
