### ISSUE TITLE
Issues running in Python 3.5 , win10

### ISSUE THREAD

**Issue by xiangyongcao** [tkipf/gcn#3]
## **Issues** 
(step by step)

- **Issue 1**: python setup.py install
> *ValueError: path 'gcn/data/' cannot end with '/'*

   -**Method:** delete the '/' (line 17)  in the setup.py 

- **Issue 2:** python train.py
> *ImportError: No module named 'cPickle'*

  -**Method:** 
  step 1: change the 'cPickle' (line 2) in utils.py as 'pickle'  
  step 2: run "python setup.py install" again
  step 3: continue run "python train.py"
  
- **Issue 3**: python train.py
>  *File "train.py", line 29, in <module>
    adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask = load_data(FLAGS.dataset)
  File "C:\Users\Xiangyong Cao\Anaconda3\lib\site-packages\gcn-1.0-py3.5.egg\gcn\utils.py", line 28, in load_data
    objects.append(pkl.load(open("data/ind.{}.{}".format(dataset_str, names[i]))))
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 0: illegal multibyte sequence*

   -**Notes:** I haven't tackled this issue and wish that the author can help dealing with is. Thanks!

**Comment by michaelosthege** [comment]
encountered the same thing a few days ago.

In `utils.py` wherever there's a `pickle.load(...)` you need to set the `encoding` parameter:

```python
pickle.load(... , encoding="latin1")
```

This was really tedious to track down..

**Comment by xiangyongcao** [comment]
Hi Michael, 

I have tried your method but still confronted the same problem. I ran this code in Python 3.5, win10.  Could you tell me your operating system and python version? Thanks.

**Comment by xiangyongcao** [comment]
Thanks for Michael's suggestion. I have tackled this issue by 

`file = open(path,'rb')
days = pkl.load(file,encoding = 'latin1')`

**Comment by tkipf** [comment]
Thanks for catching these. Adding `encoding='latin1'` unfortunately breaks python 2.7 support. I will leave this issue open for now and possibly add proper support for python 3.5 later.

**Comment by tkipf** [comment]
See https://github.com/tkipf/gcn/commit/14e6bbacabed543548cf8114a672cf1a6de85f84 for a fix that should now support both python 2 and 3.
