### ISSUE TITLE
about the citation dataset

### ISSUE THREAD

**Issue by Chunpai** [tkipf/gcn#33]
Hello Thomas,
I am wondering if you have the directed graph of the citation datasets ? Or do you have the script to generate those data ? I feel those 140 labeled nodes and testing instances are well-chosen. Do you have any idea about this ?

**Comment by tkipf** [comment]
Have a look at my other repository https://github.com/tkipf/keras-gcn or https://github.com/tkipf/pygcn for the original datasets incl appropriate dataset loaders. Hope this helps.

**Comment by Chunpai** [comment]
Thank you.
