### ISSUE TITLE
Why normalize each row of features?

### ISSUE THREAD

**Issue by hankes-garden** [tkipf/gcn#35]
If I understand correctly, the normalization is performed on each row of the feature, why? I thought it should be performed on each columns, isn't it?

```
def preprocess_features(features):
    """Row-normalize feature matrix and convert to tuple representation"""
    #??? Why Row-wise normalization? (may connect to chebshev approximation?)
    rowsum = np.array(features.sum(1))
    r_inv = np.power(rowsum, -1).flatten()
    r_inv[np.isinf(r_inv)] = 0.
    r_mat_inv = sp.diags(r_inv)
    features = r_mat_inv.dot(features)
    return sparse_to_tuple(features)
```

**Comment by tkipf** [comment]
Row-normalization in this case corresponds to individual normalization of the feature vector of each sample (since `features` is of shape N x E, where N is the number of nodes and E the number of features). Hope this answers your question.

**Comment by hankes-garden** [comment]
Hi, Kipf, Thanks for your reply. 

Could you explain a little bit more on why the row normalization is needed? I can understand colum-wise normalization/rescaling may be necessary to boost the optimization, but what is the row normalization for?

**Comment by tkipf** [comment]
Column-wise normalization would be sensitive to the number of nodes, which is quite undesirable, I suppose. Loosely speaking, normalization helps keep activations on similar levels and helps optimization.

**Comment by guotong1988** [comment]
thx
