### ISSUE TITLE
How to handle a sparsely-connected graph?

### ISSUE THREAD

**Issue by hankes-garden** [tkipf/gcn#37]
I have a connected graph of 2000 nodes, in which only 200 nodes are attached with data. However, among the resting 2800 nodes, I only care the label predication of 100 nodes. That is, there are only 300 "meaningfull" nodes (200 nodes with labels + 100 nodes to predict).

If I select these meaningful node out of graph, them form a set of isolated subgraphs. I was wondering what is the correct way to handle a sparsely-connected graph? Can the GCNN work well on such sparse graph?

What if I just use the whole graph, through I only care some nodes, in the training? will this help the performance? Any thoughts on this?

**Comment by tkipf** [comment]
I would recommend to keep all nodes and the full structure in place when you train the model as it can still provide useful information. If you do not have features for specific nodes, you can just introduce a “no-feature” feature (a binary value which is 1 for nodes without features and 0 for nodes with features). If nodes with features are described originally by a feature vector of dimension F, you now describe each node with a feature vector of dimension F+1 (where the first F features are either from the original feature vector or they are zero if there is none, and the last element is the binary “no-feature” indicator). In addition to that you could pre-compute features based on graph kernels or some node embedding (e.g. DeepWalk).

**Comment by hankes-garden** [comment]
Thanks for your suggestion!

I followed the way you implemented the semi-supervised learning, in which some nodes without data or not our targets are masked as unavailable during both the training & testing. 

One more question,  if we preserve the graph structure, do you think the number of nodes without data would affect the performance?  Because I can input the whole graph of 2000 nodes, or I can only keep a small local subgraph which includes all the meaningfull nodes while assure them are connected.

**Comment by tkipf** [comment]
It might affect performance. Best to try both settings!

**Comment by hankes-garden** [comment]
Thx!
