### ISSUE TITLE
MemoryError with large adjacency matrix during graph-level classification

### ISSUE THREAD

**Issue by gailmargolis76** [tkipf/gcn#39]
Hello, thanks for putting together this code. We have a dataset of 156 patients, each represented by a graph of 200 nodes. We are trying to do graph-level classification, so I followed the instructions, creating a sparse, block-diagonal adjacency matrix of dimensions 31,200 (156*200). But we are getting a MemoryError during the preprocessing stage, and we traced the problem to the fact that scipy sparse matrix library fails when trying to create a matrix of that size. Even after experimenting with reducing adjacency matrix size, python still chokes on the large matrix. Any suggestions as to how this issue can be bypassed?

**Comment by tkipf** [comment]
You can try creating smaller mini-batches of, say, 16-32 graphs at a time.
After each epoch these should be re-shuffled though so that examples end up
in different batches at each epoch.

**Comment by gailmargolis76** [comment]
Thanks a million for the quick response! Solved the problem by converting the adjacency matrix into a compressed sparse row matrix using scipy.
