### ISSUE TITLE
Question about processing data

### ISSUE THREAD

**Issue by kenyonke** [tkipf/gcn#41]
Hi Thomas,

I am confused about how you processed the test data as follow:

**features[test_idx_reorder, :] = features[test_idx_range, :]**

It seems that you shuffled them but their indexes in graph did not change. Could you tell me why did you do that?

Lee

**Comment by tkipf** [comment]
I recommend running this through a debugger and seeing for yourself what
this bit of code is doing :-) it’s essentially putting the nodes that we
want to keep in the right positions (without gaps, since we remove some of
them- isolated nodes without neighbors to be specific).

**Comment by kenyonke** [comment]
Thank you for your reply!

**Comment by guotong1988** [comment]
Thank you!

**Comment by SongFGH** [comment]
I I still don't understand this question! Who can help me?

**Comment by 1049451037** [comment]
@SongFGH Hi, I think it just reorders the test index to the right place, which does not matter much for using the gcn code in practice. Because using it in our own data, we just need to provide our own adjacency matrix and feature matrix.
