### ISSUE TITLE
sorry,can you help me ?

### ISSUE THREAD

**Issue by liuxiuxuhaodong** [tkipf/gcn#43]
in ind.cora.allx ,which has 1708 train samples consisted of labeled samples and non-labeled samples,but in ind.cora.ally,i find each of 1798 train samples has a label,what's wrong with non-labeled samples?we are going to predict classes that non-labeled samples belong to ,but they had get labels?

**Comment by tkipf** [comment]
The dataset indeed contains all labels, it is merely for reasons of
constructing an interesting benchmark dataset that some of the labels are
masked out.

**Comment by liuxiuxuhaodong** [comment]
thank you
