### ISSUE TITLE
preprocessing for NELL dataset

### ISSUE THREAD

**Issue by zhongboyin** [tkipf/gcn#48]
As the ICLR2017 said ：

**We assign separate relation nodes r1 and r2 for each entity pair (e1, r, e2) as (e1, r1) and (e2, r2).**

Could you take a example to explain it ?

**Comment by tkipf** [comment]
There's a different explanation for the same dataset in https://arxiv.org/abs/1603.08861 (where I got the dataset from myself). Maybe that suits you better :)

**Comment by guotong1988** [comment]
Same quesion...

**Comment by guotong1988** [comment]
Because we only have the node embedding, we don't have the edge embedding.

**Comment by guotong1988** [comment]
two nodes ...

**Comment by guotong1988** [comment]
Because we only have the node embedding, we don't have the edge embedding.
