### ISSUE TITLE
Question about NELL processing 

### ISSUE THREAD

**Issue by zhongboyin** [tkipf/gcn#51]
In your paper ICLR2017, I have noticed that the relation pair (e1, r, e2) has been divided into (e1,r1) and (e2,r2) while you process the NELL dataset. 
  
As the paper show us "We assign separate relation nodes
r1 and r2 for each entity pair (e1; r; e2) as (e1; r1) and (e2; r2)."

What's the propose of this process? how to do that? Can you take a example to explain that?

Thanks

**Comment by guotong1988** [comment]
same question...

**Comment by zhongboyin** [comment]
The reference paper said that they divided the r to two nodes： r1, r2

**Comment by guotong1988** [comment]
two nodes ...

**Comment by guotong1988** [comment]
Because we only have the node embedding, we don't have the edge embedding.
