### ISSUE TITLE
Weighted graph case

### ISSUE THREAD

**Issue by George-Wu** [tkipf/gcn#55]
Hi,

If the graph I am going to use is a weighted graph, what should I do? I think I need to change the codes that produce adj matrix in load_data() of train.py so that the adj will be a weighted version of the adjacency matrix. Is there anything else I should change? Maybe the calculation of Laplacian matrix?

Thanks

**Comment by tkipf** [comment]
For the Renormalized filters you won’t have to change anything, as the
renormalization takes care of weighted matrices as well. Depending on how
your weights are encoded you might want to prefer left-normalization (ie
division by the node degree) over symmetric normalization. The
left-normalization case is implemented in my pygcn code base.

**Comment by George-Wu** [comment]
Thanks a lot for the instant replying! So in my understanding, changing the way that the adj matrix is created will be enough for the weighted matrix case? (Not consider how well it will work)

**Comment by tkipf** [comment]
Yes

**Comment by George-Wu** [comment]
Thank you for the reply!
