### ISSUE TITLE
examples of graph pooling

### ISSUE THREAD

**Issue by yanghtr** [tkipf/gcn#61]
Hi, I wonder whether there is an example code of how to use graph pooling.
For example, I need to coarsen the graph with 1000 nodes into a graph with only 10 nodes. What is a good way to achieve this? 
In a graph whose edge connection is fixed, I need to judge which 2 nodes should be merged into 1 node in order to coarsen the graph. Should I need to specify the all this index relationship in advance? Is there any method that can automatically coarsen the graph in the training process like maxpooling in 2D CNN? 
Thank you!

**Comment by tkipf** [comment]
I recommend having a look at the technique proposed in this paper:
https://arxiv.org/pdf/1806.08804.pdf
