### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by SongFGH** [tkipf/gcn#67]
Hi, Thomas:
I know the GCN model can apply to node classification. And in your paper, I think the node classification is executed in transductive learning. 
However, why your data is ind.cora.xxx? This data is used in inductive learning!

**Comment by tkipf** [comment]
The datasets are the same for inductive and transductive learning, so this doesn't really matter (it's all from the Cora dataset). The code is using the correct splits for the respective setting. Note that GCNs work in general both for inductive and transductive learning.
