### ISSUE TITLE
Can this modle be applied to directed graphs using a normalized Laplacian matrix?

### ISSUE THREAD

**Issue by I0x0I** [tkipf/gcn#9]
Hi
I am working on classifying nodes in a strongly connected directed graph and I am wondering if it's possible to replace the Laplacian matrix used in the paper with the [normalized Laplacian matrix for directed graphs](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.linalg.laplacianmatrix.directed_laplacian_matrix.html). The GCN model seems to be compatible with the replacement, but I am not sure whether the renormalization trick and the approximation of lambda_max still work after the replacement. What do you think about applying the model to directed graphs?
Cheers

**Comment by tkipf** [comment]
This sounds like a promising research direction. I have only briefly considered this a while ago and put this idea aside since - but in principle it should be possible to use such a definition of a 'directed Laplacian' to derive a similar propagation model for GCNs. I can only encourage you to go try it out and write a paper about it :-)

**Comment by yakovzvi** [comment]
Hello

Is there a way to update any further on this metter ?

Did you had luck updating the the normalized Laplacian matrix for directed graphs.

And did it work properly thereafter ?

Thank You Very Much !!
Yanky

**Comment by tkipf** [comment]
We have a recent paper on how to deal with directed graphs (with discrete edge labels): https://arxiv.org/abs/1703.06103 

Be warned though: we don't draw any connections to spectral graph theory, so your question essentially remains unanswered.

**Comment by yakovzvi** [comment]
Dear Thomas

Thank You Very Much !!

And by the way I think only undirected graph has a symmetric adjacency matrix and therefore has real eigenvalues.

Also can you please direct me to the code of the Relational Graph Convolutional Network ?

Thank You Very Much !!
Yanky

**Comment by tkipf** [comment]
We haven't released the code for this model yet, as the model is still under development and under review. We'll probably release later this year.
