### ISSUE TITLE
Question about inferring new nodes outside the training graph

### ISSUE THREAD

**Issue by yanfan0531** [tkipf/gcn#90]
Hi, 

Thanks for your great code!

Let's say we have finished training with a graph convolutional net. In the inference stage, if a node is already contained in this graph, that would be easy to predict its label. However, if there is a new node outside the graph, with some linking info to locate its position in the original graph. How to dynamically get its embedding? Or do I need to retrain the reconstructed graph?

**Comment by tkipf** [comment]
You can just add it do the dataset (add the links to the graph and add the
feature vector to the node feature matrix) and then use a trained GCN model
to classify this new datapoint. This falls under the setting of inductive
classification, which is supported in our framework.
