### ISSUE TITLE
If the data of the same category is put together, the accuracy rate will be greatly improved. Why is this?

### ISSUE THREAD

**Issue by wmqkk** [tkipf/gcn#93]
I stumbled upon the fact that when entering data, if the same category of data is gathered together, the accuracy of the node classification will increase a lot, can you tell me the reason？thank you very much！

**Comment by tkipf** [comment]
Could you clarify what you mean by gathering together the same category of data?

**Comment by wmqkk** [comment]
The order of the data will affect the results of the experiment，when I enter data like this 0-100 are the first category, 100-200 is the second category, and 200-300 is the third category. . . the accuracy of the node classification will increase a lot.

**Comment by wmqkk** [comment]
The model trained on data that sort by labels show significant improve in accuracy than shuffled data

**Comment by tkipf** [comment]
When you permute node labels, do you permute node features and graph edges accordingly? If not, then something must be wrong, as GCNs/GNNs are invariant/covariant w.r.t. node permutations.

**Comment by wmqkk** [comment]
yes，I'm sure I permute node features and graph edges accordingly, so I feel very confused，thank you！
