### ISSUE TITLE
How can i get graph features?

### ISSUE THREAD

**Issue by JonasWangCN** [tkipf/gcn#95]
HI,
Thanks for your great work!
And i want get the feature about a full graph not a node, so i wonder if your code supports me in doing so?

**Comment by tkipf** [comment]
There is no direct support for unsupervised learning on a full-graph
representation basis, but you could for example aggregate all node
embeddings in a GCN/GAE model to receive a graph-level representation (e.g.
using a sum or an average).

**Comment by JonasWangCN** [comment]
Thanks for your reply! And I also want to know if I can do as you said without node label?

**Comment by tkipf** [comment]
Yes, that’d be possible with the GAE model:
https://github.com/tkipf/gae

**Comment by JonasWangCN** [comment]
Hello，
         I succeeded in getting the features of each node with `gae` under your guidance. But I want to know if the nodes in a graph are disconnected (meaning that there are paths between some of the nodes, but there are three or four nodes that are not connected to these nodes, all of these nodes belong to the same graph), what impact will it have?
